### ISSUE TITLE
[bug] vim-language-server don't respect .vintrc.yaml

### ISSUE THREAD

**Issue by Freed-Wu** [iamcco/vim-language-server#65]
**Describe the bug**

If .vintrc.yaml changes some vint options, vim-lsp will not diagnose.

**To Reproduce**

Add this file to your `$HOME`

```yaml
# .vintrc.yaml
cmdargs:
  severity: style_problem
  format: '{severity}:{file_path}:{line_number}:{column_number}: {description}
  ({reference})'
  color: true
```

Open a test.vim, like this:

```vim
" test.vim
se nocp
```

No diagnose information.

However, run `vint test.vim` in shell:

```
style_problem:a.vim:1:1: Use the full option name `nocompatible` instead of `nocp` (:help option-summary)
warning:a.vim:1:1: Do not use nocompatible which has unexpected effects (:help nocompatible)
```

I think it can be solved by pass command option to vint.

**Desktop (please complete the following information):**
 - OS: linux 5.14
